### ISSUE TITLE
Errors trying to compile TinySerial example

### ISSUE THREAD

**Issue by davoau** [Alex079/TinySuite#7]
Hi,
I am wanting to use a ATTiny85 with serial communication (RX and TX) to an ESP2688 using pins PB0 (TX) and PB1 (RX), with interrupts on PB2 and PB4 to detect reed switches.
I tried with SoftwareSerial but couldn't get it to work, then I came across your TinySuite hoping it would work/help.

 I am trying to use TinySerial library. I have used your example:
`examples/uart-print/main.cpp`
```
#include <avr/interrupt.h>
#include <Arduino.h>
#include <TinySerial.h>
#include <TinyTimer1Compare.h>
#include <TinyPinChangeB.h>

TinySerial serial(PB2, PB1, Timer1Compare, PinChangeB);

void setup() {
  sei();
  serial.begin(9600);
}

// continuously output on PB1 (pin 6) at 9600 baud using Timer1 in compare mode
void loop() {
  delay(5000);
  serial.print(F("this is a test\n"));
}
```
But I get the following error when trying to compile in Arduino IDE 2.2.0:
```
C:\Users\Default User.DESKTOP-UR53KBO\AppData\Local\Temp\arduino\sketches\726D5ED6F4FD068CAC41B0B46184620E\core\Tone.cpp.o (symbol from plugin): In function `_noTone':
(.text+0x0): multiple definition of `__vector_4'
C:\Users\Default User.DESKTOP-UR53KBO\AppData\Local\Temp\arduino\sketches\726D5ED6F4FD068CAC41B0B46184620E\libraries\TinySuite\TinyTimer1Overflow.cpp.o (symbol from plugin):(.text+0x0): first defined here
C:\Users\Default User.DESKTOP-UR53KBO\AppData\Local\Temp\arduino\sketches\726D5ED6F4FD068CAC41B0B46184620E\core\pins_arduino.c.o (symbol from plugin): In function `_turnOnPWM':
(.text+0x0): multiple definition of `__vector_5'
C:\Users\Default User.DESKTOP-UR53KBO\AppData\Local\Temp\arduino\sketches\726D5ED6F4FD068CAC41B0B46184620E\libraries\TinySuite\TinyTimer0Overflow.cpp.o (symbol from plugin):(.text+0x0): first defined here
collect2.exe: error: ld returned 1 exit status

Using library TinySuite at version 2.1.0 in folder: C:\Users\Default User.DESKTOP-UR53KBO\Documents\Arduino\libraries\TinySuite 
exit status 1

Compilation error: exit status 1
```

Do you know what's happening and if there a fix
Thanks

**Comment by Alex079** [comment]
Hello,

Thanks for reporting the problem.

What happens is that several pieces of code are trying to define their own timer interrupts.
In particular,
Tone.cpp and TinyTimer1Overflow.cpp both define the Timer1 overflow interrupt vector4
pins_arduino.c and TinyTimer0Overflow.cpp both define Timer0 interrupt vector5

To my knowledge, there is no easy way around this. I made this library to be independent from arduino core, but this example does depend on it. I assume that the core has changed, and I need to update or delete the example.
Let me try to run it with actual arduino IDE.

**Comment by Alex079** [comment]
![Screenshot_20231113_212958](https://github.com/Alex079/TinySuite/assets/21042652/c3f8bb7d-5381-4cf9-8844-cd7f6c5e7c49)
Do you use settings similar to these ones?

**Comment by davoau** [comment]
![Screenshot 2023-11-18 115256](https://github.com/Alex079/TinySuite/assets/81886517/8d232d01-d614-4c4e-aa9a-ecb682f740d4)

This is the setting I have.

**Comment by Alex079** [comment]
OK. Could you try disabling the "Millis and Tone" and "Bootloader" support, if possible?
